---
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
knitr::opts_chunk$set(comment = "")
```

## Econ 270 Homework 2

## Combinatorics

You toss a coin 5 times. What is the probability of obtaining exactly 3 heads?

How many ways can you rearrange the letters in 'chocolate'?

Moderately hard: There are 23 people in a room. What is the probability that a birthday is shared among at least two people in the room?

book problems: 4.21, 4.25, 3.24

Hard: A derangement is a permutation such that none of the elements are in their original order. How many derangements are there of 4 items? [hint: the general solution uses recursion]

## Basic probability

3.2, 3.5, 3.6, 3.10, 3.12, 3.23,

## Probability Definitions

3.1, 3.7, 3.9

## Conditional Probability

You are presented with 3 boxes. One contains two gold coins, one contains two silver coins, and one contains one gold coin and one silver coin. You randomly choose a coin and observe that it is a gold coin. What is the probability that the other coin in the box is a gold coin?

3.11, 3.14, 3.15, 3.25

## Bayes Theorem

A cancer test correctly predicts that you have cancer 99\% of the time for individuals with cancer, and correctly predicts that you don't have cancer 99\% of the time for indivudlas who don't have cancer. Suppose that 1\% of the population has cancer. You take a cancer test, and the test tells you that you have cancer. What is the probability that you have cancer?

3.19b